# Solo disparar el workflow cuando se haya un push con un tag etiquetado con "deloy-site..."
on:
  push:
    tags:
      - 'deploy-site*'

jobs:
  deploy:
    #runs-on: macos-latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Parse blog
        run: npm run blog
      - name: Build static site
        run: npm run build
      # - name: Deploy
      #   uses: s0/git-publish-subdir-action@master # https://github.com/s0/git-publish-subdir-action
      #   env:
      #     REPO: self
      #     BRANCH: master
      #     FOLDER: www
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Depoy
        uses: peaceiris/actions-gh-pages@v3
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./www
            publish_branch: master  # deploying branch
            cname: dlopezcastellote.dev